"""init reading_speeds

Revision ID: 0001_init
Revises:
Create Date: 2026-05-16 17:17:30.831313

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_init"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reading_speeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("pages_per_hour", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_speeds_sub"), "reading_speeds", ["sub"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_speeds_sub"), table_name="reading_speeds")
    op.drop_table("reading_speeds")
    # ### end Alembic commands ###
